# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_indexs_productinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='num',
            field=models.IntegerField(),
        ),
    ]
