# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_auto_20160117_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='issue_type',
            field=models.CharField(default='stock', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='cn_name',
            field=models.CharField(max_length=20),
        ),
    ]
